---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by orin.
--- DateTime: 3.07.2021 19:21
---
local baseConditionFunc = nil;

function onInit()
    baseConditionFunc = EffectManagerPFRPG2.checkConditional;
    EffectManagerPFRPG2.checkConditional = customConditionFunc;
    OptionsManager.registerOption2("ShieldCondLog", false, "option_shield_cond_header", "option_shield_cond_logging_label", "option_entry_cycler", { labels = "chat|console", values="chat|console", baselabel = "option_val_off", baseval="off", default="off"});
end

function customConditionFunc(rActor, nodeEffect, aConditions, rTarget, aIgnore)

    logToChat(rActor, nodeEffect, aConditions, rTarget, aIgnore);

    local retVal = baseConditionFunc(rActor, nodeEffect, aConditions, rTarget, aIgnore);

    logToChat("CONDITION BASE RESULT : ", retVal);

    if aConditions[1] then
        local sLower = aConditions[1]:lower();
        logToChat("FIRST CONDITON : ", sLower);
        if sLower == 'shieldup' and retVal == true then
            logToChat("Checking Shield UP");
            local sNodeType, nodeActor = ActorManager.getTypeAndNode(rActor);
            logToChat("Checking Shield UP , " , nodeActor);
            if nodeActor then
                local nShieldRaised = DB.getValue(nodeActor, "ac.sources.shieldraised", 0);
                local nShieldBonus = DB.getValue(nodeActor, "ac.sources.shield", 0);
                logToChat("Shield Status , Shield bonus : ", nShieldRaised,nShieldBonus);
                if nShieldRaised <= 0 or nShieldBonus <= 0 then
                    retVal = false;
                end
            end
        end
    end



    logToChat("CONDITION FINAL RESULT : ", retVal);
    return retVal;

end

function logToChat(...)
    local logOption = OptionsManager.getOption("ShieldCondLog"):lower();

    if logOption == "chat" then
        Debug.chat(...);
    elseif logOption == "console" then
        Debug.chat(...);
    end

end
