---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by orin.
--- DateTime: 9.06.2021 09:45
---

local baseFunc = nil;
local chatLogEnabled = true;

-- { s'type' = s'cast', s'label' = s'sddsdsf', s'order' = #1, s'sTargeting' = s'', s'range' = s'R', s'savetraits' = s'VsRef', s'savemod' = #-1, s'dcstat' = s'intelligence', s'onmissdamage' = s'', s'save' = s'reflex', s'crit' = #20, s'stat' = s'wisdom', s'modifier' = #5 }
-- { s'type' = s'cast', s'label' = s'sddsdsf', s'order' = #1, s'sTargeting' = s'', s'range' = s'R', s'savetraits' = s'VsRef', s'savemod' = #-1, s'dcstat' = s'intelligence', s'onmissdamage' = s'', s'save' = s'will', s'crit' = #20, s'stat' = s'wisdom', s'modifier' = #5 }
-- { s'type' = s'cast', s'savetraits' = s'VsRef', s'subtype' = s'atk', s'order' = #1, s'sTargeting' = s'', s'range' = s'R', s'savemod' = #-1, s'dcstat' = s'intelligence', s'save' = s'fortitude', s'onmissdamage' = s'', s'crit' = #20, s'modifier' = #5, s'stat' = s'wisdom', s'label' = s'sddsdsf' }
function onInit()
    baseFunc = ActionAttack.getRoll;
    ActionAttack.getRoll = customFunc;
    OptionsManager.registerOption2("SpellVsDcLog", false, "option_spvsdc_header", "option_spvsdc_logging_label", "option_entry_cycler", { labels = "chat|console", values="chat|console", baselabel = "option_val_off", baseval="off", default="off"});
end

function customFunc(rActor, rAction)

    logToChat(rActor, rAction);

    local willModifyRoll = false;
    local vsDcKeyword = nil;

    if rAction.type == "cast" and rAction.savemod == -1 then
        logToChat("VsDc Roll mod started");
        willModifyRoll = true;
        if rAction.save == "reflex" then
            vsDcKeyword = "REF";
        elseif rAction.save == "fortitude" then
            vsDcKeyword = "FORT";
        elseif rAction.save == "will" then
            vsDcKeyword = "WILL";
        else
            willModifyRoll = false;
            logToChat("VsDc type undefined");
        end
    end


    if willModifyRoll == true then
        rAction.vsdc = vsDcKeyword;
        logToChat("VsDc Roll mod DONE");
    end


    local rRoll = baseFunc(rActor, rAction);

    logToChat(rRoll);

    return rRoll;

end

function logToChat(...)
    local logOption = OptionsManager.getOption("SpellVsDcLog"):lower();

    if logOption == "chat" then
        Debug.chat(...);
    elseif logOption == "console" then
        Debug.chat(...);
    end

end
